import React from "react";
import { Alert } from "react-native";
import { fireEvent, render, waitFor } from "@testing-library/react-native";
const mockParams=jest.fn(),mockPush=jest.fn(),mockBack=jest.fn(),mockUser=jest.fn(),mockFrom=jest.fn();
const mockGetLists=jest.fn(),mockGetList=jest.fn(),mockSaveList=jest.fn();
jest.mock("expo-router",()=>{const React=require("react");const {View}=require("react-native");return{Stack:{Screen:()=> <View/>},router:{push:(...a:any[])=>mockPush(...a),back:(...a:any[])=>mockBack(...a)},useLocalSearchParams:()=>mockParams()}});
jest.mock("react-native-safe-area-context",()=>({SafeAreaView:({children}:any)=>children,useSafeAreaInsets:()=>({top:0})}));
jest.mock("@expo/vector-icons",()=>{const React=require("react");const {View}=require("react-native");const Icon=(p:any)=><View {...p}/>;Icon.glyphMap={};return{Ionicons:Icon}});
jest.mock("@/hooks/useTheme",()=>({useTheme:()=>({colors:{background:"white",border:{light:"gray"},text:{primary:"black",secondary:"gray",tertiary:"gray"},input:{background:"#eee"}}})}));
jest.mock("@/components/save-button",()=>({SaveButton:()=>null}));
jest.mock("@/lib/supabase",()=>({supabase:{auth:{getUser:(...a:any[])=>mockUser(...a)},from:(...a:any[])=>mockFrom(...a),storage:{from:()=>({createSignedUrl:jest.fn()})}}}));
jest.mock("@/lib/local-grocery-lists",()=>({getLocalGroceryLists:(...a:any[])=>mockGetLists(...a),getLocalGroceryListById:(...a:any[])=>mockGetList(...a),saveLocalGroceryList:(...a:any[])=>mockSaveList(...a)}));
import RecipeDetailScreen from "@/app/recipe/[id]";
const alert=jest.spyOn(Alert,"alert");
const uuid="11111111-1111-4111-8111-111111111111";
const dbRecipe={id:uuid,user_id:"author-1",title:"Database Soup",description:"Stored",difficulty:"Easy",tags:["Dinner","cozy"],cover_image_url:"db.jpg",cover_image_path:null,cover_media:[],prep_time_minutes:5,cook_time_minutes:10,additional_time_minutes:0,total_time_minutes:15,servings:3,ingredients:[{id:"i1",position:1,quantity:"2",unit:"cups",name:"Carrot"},{position:0,quantity:"1",unit:"tbsp",name:"Oil"},{name:" "}],steps:[{position:1,instruction:"Simmer"},{position:0,instruction:"Chop"},{instruction:" "}]};

describe("recipe detail",()=>{
 beforeEach(()=>{jest.clearAllMocks();mockParams.mockReturnValue({id:"1"});mockUser.mockResolvedValue({data:{user:null},error:null});mockGetLists.mockResolvedValue([{id:"list1",title:"Weekly",date:"Today",items:[]}]);mockGetList.mockResolvedValue({id:"list1",title:"Weekly",date:"Today",isPinned:false,items:[]});mockSaveList.mockImplementation(async(v:any)=>({...v,id:v.id||"new-local"}));mockFrom.mockImplementation((table:string)=>{if(table==="recipes")return{select:()=>({eq:()=>({single:async()=>({data:dbRecipe,error:null})})})};if(table==="profiles")return{select:()=>({eq:()=>({maybeSingle:async()=>({data:{id:"author-1",full_name:"Avery Farmer",username:"avery",avatar_url:"avatar.jpg"},error:null})})})};if(table==="grocery_lists")return{select:()=>({eq:()=>({order:async()=>({data:[{id:"db-list",title:"Cloud",created_at:"2026-01-01"}],error:null})})}),insert:()=>({select:()=>({single:async()=>({data:{id:"created-db"},error:null})})})};return{select:()=>({eq:()=>({order:async()=>({data:[],error:null})})}),insert:async()=>({error:null})};});});
 it("renders a local recipe and adds ingredients to an existing local list",async()=>{const s=await render(<RecipeDetailScreen/>);expect(s.getByText("Banana Blueberry")).toBeTruthy();expect(s.getByText("Banana")).toBeTruthy();expect(s.getByText("Directions")).toBeTruthy();await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(s.getByText("Weekly")).toBeTruthy());await fireEvent.press(s.getByText("Weekly"));await waitFor(()=>expect(mockSaveList).toHaveBeenCalledWith(expect.objectContaining({id:"list1",items:expect.any(Array)})));expect(mockPush).toHaveBeenCalledWith("/grocery-list/list1");});
 it("creates a new local grocery list",async()=>{const s=await render(<RecipeDetailScreen/>);await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(s.getByText("Create new grocery list")).toBeTruthy());await fireEvent.press(s.getByText("Create new grocery list"));await waitFor(()=>expect(mockSaveList).toHaveBeenCalledWith(expect.objectContaining({title:"Banana Blueberry List"})));expect(mockPush).toHaveBeenCalledWith("/grocery-list/new-local");});
 it("deduplicates local ingredients and handles missing lists",async()=>{mockGetList.mockResolvedValueOnce({id:"list1",title:"Weekly",items:[{name:"Banana",unit:"cups"},{name:"Blueberry",unit:"handful"}]});const s=await render(<RecipeDetailScreen/>);await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(s.getByText("Weekly")).toBeTruthy());await fireEvent.press(s.getByText("Weekly"));await waitFor(()=>expect(alert).toHaveBeenCalledWith("Nothing new to add",expect.any(String)));});
 it("shows missing recipe state and navigates back",async()=>{mockParams.mockReturnValue({id:"missing"});const s=await render(<RecipeDetailScreen/>);expect(s.getByText("Recipe not found")).toBeTruthy();await fireEvent.press(s.getByLabelText("Go back"));expect(mockBack).toHaveBeenCalled();});
 it("reports grocery-list loading errors",async()=>{mockUser.mockResolvedValue({data:{user:null},error:new Error("auth")});const s=await render(<RecipeDetailScreen/>);await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(alert).toHaveBeenCalledWith("Could not load grocery lists","auth"));});
 it("loads a database recipe and adds its ingredients to an account list",async()=>{mockParams.mockReturnValue({id:uuid});mockUser.mockResolvedValue({data:{user:{id:"u"}},error:null});const s=await render(<RecipeDetailScreen/>);await waitFor(()=>expect(s.getByText("Database Soup")).toBeTruthy());expect(s.getByText("15 min")).toBeTruthy();expect(s.getByText("Easy")).toBeTruthy();expect(s.getByText("#Dinner")).toBeTruthy();expect(s.getByText("#cozy")).toBeTruthy();await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(s.getByText("Cloud")).toBeTruthy());await fireEvent.press(s.getByText("Cloud"));await waitFor(()=>expect(mockPush).toHaveBeenCalledWith("/grocery-list/db-list"));});
 it("shows an edit button for the recipe owner",async()=>{mockParams.mockReturnValue({id:uuid});mockUser.mockResolvedValue({data:{user:{id:"author-1"}},error:null});const s=await render(<RecipeDetailScreen/>);await waitFor(()=>expect(s.getByLabelText("Edit recipe")).toBeTruthy());await fireEvent.press(s.getByLabelText("Edit recipe"));expect(mockPush).toHaveBeenCalledWith({pathname:"/recipe/new",params:{recipeId:uuid,coverImageUrl:"db.jpg"}});});
 it("shows the recipe author and opens their profile",async()=>{mockParams.mockReturnValue({id:uuid});const s=await render(<RecipeDetailScreen/>);await waitFor(()=>expect(s.getByText("Avery Farmer")).toBeTruthy());await fireEvent.press(s.getByLabelText("View Avery Farmer's profile"));expect(mockPush).toHaveBeenCalledWith("/user/author-1");});

 it("creates a database grocery list for signed-in users",async()=>{mockParams.mockReturnValue({id:uuid});mockUser.mockResolvedValue({data:{user:{id:"u"}},error:null});const s=await render(<RecipeDetailScreen/>);await waitFor(()=>expect(s.getByText("Database Soup")).toBeTruthy());await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(s.getByText("Create new grocery list")).toBeTruthy());await fireEvent.press(s.getByText("Create new grocery list"));await waitFor(()=>expect(mockPush).toHaveBeenCalledWith("/grocery-list/created-db"));expect(alert).toHaveBeenCalledWith("Grocery list created",expect.any(String));});
 it("handles database recipes without ingredients or media",async()=>{mockParams.mockReturnValue({id:uuid});mockFrom.mockImplementation((table:string)=>table==="recipes"?{select:()=>({eq:()=>({single:async()=>({data:{...dbRecipe,description:null,cover_image_url:null,cover_image_path:null,cover_media:null,ingredients:null,steps:null,total_time_minutes:0,servings:null},error:null})})})}:{select:()=>({eq:()=>({order:async()=>({data:[],error:null})})})});const s=await render(<RecipeDetailScreen/>);await waitFor(()=>expect(s.getByText("Database Soup")).toBeTruthy());expect(s.queryByText("Stored")).toBeNull();await fireEvent.press(s.getByText("Add ingredients to grocery list"));expect(alert).toHaveBeenCalledWith("No ingredients",expect.any(String));});
 it("shows database load failures as missing recipes",async()=>{mockParams.mockReturnValue({id:uuid});mockFrom.mockReturnValue({select:()=>({eq:()=>({single:async()=>({data:null,error:new Error("gone")})})})});const s=await render(<RecipeDetailScreen/>);await waitFor(()=>expect(s.getByText("Recipe not found")).toBeTruthy());});
 it("handles a missing local grocery list",async()=>{mockGetList.mockResolvedValue(null);const s=await render(<RecipeDetailScreen/>);await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(s.getByText("Weekly")).toBeTruthy());await fireEvent.press(s.getByText("Weekly"));await waitFor(()=>expect(alert).toHaveBeenCalledWith("List not found",expect.any(String)));});
 it("reports partially duplicated local ingredients",async()=>{mockGetList.mockResolvedValue({id:"list1",title:"Weekly",date:"Today",isPinned:true,items:[{id:"old",name:"Banana",unit:"cups",checked:false}]});const s=await render(<RecipeDetailScreen/>);await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(s.getByText("Weekly")).toBeTruthy());await fireEvent.press(s.getByText("Weekly"));await waitFor(()=>expect(alert).toHaveBeenCalledWith("Grocery list updated",expect.stringContaining("duplicate")));});
 it("requires authentication when an account list is chosen",async()=>{mockParams.mockReturnValue({id:uuid});mockUser.mockResolvedValue({data:{user:{id:"u"}},error:null});const s=await render(<RecipeDetailScreen/>);await waitFor(()=>expect(s.getByText("Database Soup")).toBeTruthy());await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(s.getByText("Cloud")).toBeTruthy());mockUser.mockResolvedValue({data:{user:null},error:null});await fireEvent.press(s.getByText("Cloud"));await waitFor(()=>expect(alert).toHaveBeenCalledWith("Not signed in",expect.any(String)));});
 it("reports account-list item query errors",async()=>{mockParams.mockReturnValue({id:uuid});mockUser.mockResolvedValue({data:{user:{id:"u"}},error:null});mockFrom.mockImplementation((table:string)=>{if(table==="recipes")return{select:()=>({eq:()=>({single:async()=>({data:dbRecipe,error:null})})})};if(table==="grocery_lists")return{select:()=>({eq:()=>({order:async()=>({data:[{id:"db-list",title:"Cloud",created_at:null}],error:null})})})};return{select:()=>({eq:()=>({order:async()=>({data:null,error:new Error("items offline")})})})};});const s=await render(<RecipeDetailScreen/>);await waitFor(()=>expect(s.getByText("Database Soup")).toBeTruthy());await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(s.getByText("Cloud")).toBeTruthy());await fireEvent.press(s.getByText("Cloud"));await waitFor(()=>expect(alert).toHaveBeenCalledWith("Could not update grocery list","items offline"));});
 it.each([["some",[{id:"old",list_id:"db-list",user_id:"u",position:null,quantity:"2",unit:"cups",name:"Carrot",is_checked:false}],"Grocery list updated"],["all",[{id:"a",list_id:"db-list",user_id:"u",position:0,quantity:"2",unit:"cups",name:"Carrot",is_checked:false},{id:"b",list_id:"db-list",user_id:"u",position:1,quantity:"1",unit:"tbsp",name:"Oil",is_checked:false}],"Nothing new to add"]])("handles %s duplicate account ingredients",async(_kind,existing,heading)=>{mockParams.mockReturnValue({id:uuid});mockUser.mockResolvedValue({data:{user:{id:"u"}},error:null});mockFrom.mockImplementation((table:string)=>{if(table==="recipes")return{select:()=>({eq:()=>({single:async()=>({data:dbRecipe,error:null})})})};if(table==="grocery_lists")return{select:()=>({eq:()=>({order:async()=>({data:[{id:"db-list",title:"Cloud",created_at:"invalid"}],error:null})})})};return{select:()=>({eq:()=>({order:async()=>({data:existing,error:null})})}),insert:async()=>({error:null})};});const s=await render(<RecipeDetailScreen/>);await waitFor(()=>expect(s.getByText("Database Soup")).toBeTruthy());await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(s.getByText("Cloud")).toBeTruthy());await fireEvent.press(s.getByText("Cloud"));await waitFor(()=>expect(alert).toHaveBeenCalledWith(heading,expect.any(String)));});
 it("reports account-list insertion failures",async()=>{mockParams.mockReturnValue({id:uuid});mockUser.mockResolvedValue({data:{user:{id:"u"}},error:null});mockFrom.mockImplementation((table:string)=>{if(table==="recipes")return{select:()=>({eq:()=>({single:async()=>({data:dbRecipe,error:null})})})};if(table==="grocery_lists")return{select:()=>({eq:()=>({order:async()=>({data:[{id:"db-list",title:"Cloud",created_at:"2026"}],error:null})})})};return{select:()=>({eq:()=>({order:async()=>({data:[],error:null})})}),insert:async()=>({error:new Error("insert failed")})};});const s=await render(<RecipeDetailScreen/>);await waitFor(()=>expect(s.getByText("Database Soup")).toBeTruthy());await fireEvent.press(s.getByText("Add ingredients to grocery list"));await waitFor(()=>expect(s.getByText("Cloud")).toBeTruthy());await fireEvent.press(s.getByText("Cloud"));await waitFor(()=>expect(alert).toHaveBeenCalledWith("Could not update grocery list","insert failed"));});
 it("navigates back from a valid recipe",async()=>{const s=await render(<RecipeDetailScreen/>);await fireEvent.press(s.getByLabelText("Go back"));expect(mockBack).toHaveBeenCalled();});
});

